package ch.epfl.tchu;

public enum PlayerMethod {
    INIT_PLAYERS,
    RECEIVE_INFO,
    UPDATE_STATE,
    SET_INITIAL_TICKET_CHOICE,
    CHOOSE_INITIAL_TICKETS,
    NEXT_TURN,
    CHOOSE_TICKETS,
    DRAW_SLOT,
    CLAIMED_ROUTE,
    INITIAL_CLAIM_CARDS,
    CHOOSE_ADDITIONAL_CARDS
}
